### PR TITLE
[#279] Fix: Invalid "Project" struct when initializing Elixir project with custom module name

### LINKED ISSUE #279: Fix: Invalid "Project" struct when initializing Elixir project with custom module name
## Issue

Mix project generator allows users to define a custom module name, resulting in some file names can be different from the app name.

Here are generated projects with `mix new mix_project_with_custom_module --module CustomModule`

|                    | Screenshot  |
|--------------------|---|
| File structure             | image |
| Base module | image |

Compare the above screenshot with the following `Project` struct. The `base_module` and `base_path` are invalid, and properties related to the web should be nil because it is a plain Elixir project, not a web project.
 
```elixir
%NimbleTemplate.Projects.Project{
  base_module: "MixProjectWithCustomModule", # Invalid
  base_path: "lib/mix_project_with_custom_module", # Invalid
  base_test_path: "test/mix_project_with_custom_module", # Invalid
  otp_app: :mix_project_with_custom_module,
  web_module: "MixProjectWithCustomModuleWeb", # Should be nil
  web_path: "lib/mix_project_with_custom_module_web",  # Should be nil
  web_test_path: "test/mix_project_with_custom_module_web",  # Should be nil
  alpine_version: "3.14.6",
  elixir_version: "1.14.0",
  erlang_version: "25.0.4",
  node_asdf_version: "16.15.0",
  elixir_asdf_version: "1.14.0-otp-25",
  api_project?: false,
  live_project?: false,
  web_project?: false,
  mix_project?: false,
  installed_addons: []
}
```

## Expected

The `Project` struct modules and paths should match the actual project structure.
 
## Steps to reproduce

1. Generate an Elixir project with `mix new awesome_project --module CustomModule`
2. Add `nimble_template` to the project dependency.
3. Run iex console with a compiled application, `iex -S mix`
4. Initialize the Project struct with `NimbleTemplate.Projects.Project.new()` and observe paths

### PR DESCRIPTION
**Pull request by hanam1ni**
- Closes #279 

## What happened 👀

- Update the `Project` struct to contain more accurate information about the project structure.
- Add typespecs to the `Project` module

## Insight 📝

- For the mix project, it needs to get the base module from the `mix.exs` file because the mix project does not have access to `Mix.Phoenix.base/0`
- For the mix project, since the generated project does not have the structure same as the web project, so it does not have `base_path` and web-related path and modules. Therefore, all the fields related to that are set to `nil`

## Proof Of Work 📹

| Project type                   | Project structure | `Project` struct |
|--------------------------------|-------------------|------------------|
| Mix project                    |image  | image|
| Mix project with custom module |image | image |
| Web project                    |image |image|
| Web project with custom module |image   |image|

### CODE REVIEW

**Review by Nihisil — APPROVED** [review]

**Review by bterone — APPROVED** [review]

File: test/nimble_template/projects/project_test.exs [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    } do
+      in_test_project(test_project_path, fn ->
+        project = Project.new(mix: true)
+
+        assert project.base_module == "SampleCustomModule"
+        assert project.otp_app == :nimble_template
+      end)
+    end
+
+    test "given web project, returns valid project with valid modules and paths", %{
```
Comment (andyduong1920) [inline test/nimble_template/projects/project_test.exs:40]: should we add the test for custom web module name, like `SampleCustomModule` for

-web
- api
- liveview

projects @hanam1ni

**Review by andyduong1920 — APPROVED** [review]
just a small comment @hanam1ni

File: test/nimble_template/projects/project_test.exs (hunk 1 above)
Comment (hanam1ni) [reply test/nimble_template/projects/project_test.exs:40]: Updated in [4453790](https://github.com/nimblehq/elixir-templates/pull/280/commits/44537909dc7c23f29941de082714b84f2f0ddcb1)
